#%RAML 1.0
title: zipcodes
/project1/{zipcodes}:
    get:
      responses:
        200:
          body:
            application/json:
              example:
                {
                  "zipcodes": "20904"
                }
    
          