%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo({
  "item": {
    "ID": "20540",
    "CountiesArea": "495",
    "ZipCodePopulation": "48841",
    "HouseholdsPerZipcode": "16271.0000",
    "WhitePop": "25336",
    "BlackPop": "9987",
    "HispanicPop": "16532",
    "AsianPop": "5618",
    "IndianPop": "733",
    "HawaiianPop": "161",
    "OtherPop": "9577",
    "MalePop": "23961",
    "FemalePop": "24880",
    "PersonsPerHousehold": "2.97",
    "AverageHouseValue": "417400.00",
    "IncomePerHousehold": "94211.00",
    "MedianAge": "35.40",
    "MedianAgeMale": "34.10",
    "MedianAgeFemale": "36.80",
    "AverageFamilySize": "3.45",
    "Bus03Establishments": "1000",
    "Bus03Employment": "9929",
    "Bus03PayrollQuarter1": "106042",
    "Bus03PayrollAnnual": "440421",
    "Bus03EmploymentFlag": " ",
    "CBSAPop2003": "5582170",
    "CBSADivPop2003": "1205162",
    "DeliveryActive": "19899",
    "DeliveryBusiness": "869",
    "DeliveryResidential": "17976",
    "DeliverySpecial": "17976",
    "DeliveryBox": "0",
    "DeliverySFDU": "10756",
    "DeliveryMFDU": "5163",
    "PopulationEstimate": "53388",
    "_109thDistrict": "0",
    "_109thArea": "0",
    "_110thDistrict": "08",
    "_110thArea": "859.85",
    "GrowthRank": "0",
    "GrowthHousingUnits2003": "0",
    "GrowthHousingUnits2004": "0",
    "GrowthIncreaseNumber": "0",
    "GrowthIncreasePercentage": "0.00",
    "Latitude": "39.041070",
    "Longitude": "-77.045049",
    "Elevation": "397.00",
    "AreaLand": "7.564000",
    "AreaWater": "0.035000",
    "Primary": "P",
    "State": "MD",
    "CityType": "P",
    "CityAliasType": null,
    "Classification": " ",
    "ZipCode": "20902",
    "CityAliasAbbr": null,
    "AreaCode": "301/240",
    "AreaCodeTemp": "301/240",
    "AreaCodeTest": null,
    "City": "SILVER SPRING",
    "CityAliasName": "SILVER SPRING",
    "CountyName": "MONTGOMERY",
    "CountyFIPS": "031",
    "StateFIPS": "24",
    "CountyANSI": "031",
    "StateANSI": "24",
    "TimeZone": "5",
    "DayLightSaving": "Y",
    "MSA": "8872",
    "PMSA": "8840",
    "PMSAName": "Washington, DC-MD-VA-WV PMSA",
    "CSA": "548",
    "CSAName": "Washington-Baltimore-Arlington, DC-MD-VA-WV-PA",
    "CBSA": "47900",
    "CBSA_DIV": "23224",
    "CBSA_DIV_Name": "Frederick-Gaithersburg-Rockville, MD",
    "CBSA_Type": "Metro",
    "CBSA_Name": "Washington-Arlington-Alexandria, DC-VA-MD-WV",
    "MSAName": "Washington-Baltimore, DC-MD-VA-WV CMSA",
    "Region": "South",
    "Division": "South Atlantic",
    "MailingName": "Y",
    "MultiCounty": " ",
    "Prev": "20901",
    "Next": "20903",
    "CityStateKey": "V24373",
    "PreferredLastLineKey": "V24373",
    "PreferredLastLineName": "SILVER SPRING",
    "IntroDateZIP": "<2004-10",
    "IntroDateAlias": "<2004-10",
    "FacilityCode": "P",
    "CityDeliveryIndicator": "Y",
    "CarrierRouteRateSortation": "B",
    "FinanceNumber": "238478",
    "UniqueZIPName": null,
    "MixedCaseCity": "Silver Spring",
    "MixedCaseAlias": "Silver Spring",
    "SSA_State_County_Code": "21150",
    "Medicare_CBSA_Code": "43524",
    "Medicare_CBSA_Name": "Silver Spring-Frederick-Rockville, MD",
    "Medicare_CBSA_Type": "Metro",
    "Medicare_Rating_Area_ID": "3",
    "StateFullName": "Maryland",
    "CountyMixedCase": null,
    "CityAliases": {
      "Item": [
        {
          "ID": "20540",
          "Primary": "P",
          "CityType": "P",
          "CityAliasName": "SILVER SPRING",
          "CityStateKey": "V24373",
          "FacilityCode": "P",
          "MixedCaseAlias": "Silver Spring"
        },
        {
          "ID": "20541",
          "Primary": " ",
          "CityType": "B",
          "CityAliasName": "WHEATON",
          "CityStateKey": "V24639",
          "FacilityCode": "B",
          "MixedCaseAlias": "Wheaton"
        }
      ]
    }
  }
})